version: "3"
services:
  server:
    build: ./server
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - server
